name: Windows VPS Ngrok

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup User
        shell: cmd
        run: |
          net user runneradmin 123456Aa@
          net localgroup administrators runneradmin /add
          exit /b 0

      - name: Enable RDP
        run: |
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download ngrok
        run: |
          curl -L -o ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip
          tar -xf ngrok.zip

      - name: Add Auth Token
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

      - name: Start Tunnel
        run: |
          start ngrok tcp 3389

      - name: Show IP
        run: |
          timeout /t 10
          curl http://127.0.0.1:4040/api/tunnels

      - name: Keep Alive
        run: |
          ping -t 127.0.0.1
