name: Windows VPS Tailscale

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup User
        shell: cmd
        run: |
          net user runneradmin 123456Aa@
          net localgroup administrators runneradmin /add
          exit /b 0

      - name: Enable RDP
        run: |
          reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Download Tailscale
        run: |
          curl -L -o tailscale.msi https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi

      - name: Install Tailscale
        shell: cmd
        run: |
          msiexec /i tailscale.msi /quiet /norestart

      - name: Start Tailscale
        run: |
          "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TS_KEY }} --hostname=github-vps

      - name: Show IP
        run: |
          echo ===== YOUR VPS IP =====
          "C:\Program Files\Tailscale\tailscale.exe" ip -4

      - name: Keep Alive
        run: |
          ping -t 127.0.0.1
